### ISSUE TITLE
Unmet peer dependency warning

### ISSUE THREAD

**Issue by Pwntus** [goldwasserexchange/serverless-plugin-webpack#1]
Since serverless will most likely be installed globally, is the ` "serverless": "1.x"` in package.json necessary?

I'm getting `UNMET PEER DEPENDENCY serverless@1.x` every time I deploy.

Great plugin by the way!

**Comment by jogold** [comment]
Hi @Pwntus, 

I always install `serverless` locally in order to handle different versions with different projects, that's why I haven't noticed.

I understand that the warning can be annoying, I'll remove the peer dependency and update the package.

**Comment by jogold** [comment]
See 9c61de257a8065744a16d2f77a07e932245701a8.
