### ISSUE TITLE
Same name different folder...

### ISSUE THREAD

**Issue by colinfindlay-nz** [goldwasserexchange/serverless-plugin-webpack#15]
If I have multiple handlers with the same name, but in different folders, the plugin deploys the first match found :-(

i.e

I have:
```
functions:
  getUsers:
    handler:            src/users/handler.get
    events:
     - http:
         path:        api/users
         method:      get
  getBananas:
    handler:            src/bananas/handler.get
    events:
      - http:
          path:        api/bananas
          method:      get
```
Currently - the lambda for getBananas contains the code found in `src/users/handler.get` as it seems to match the first found handler.get - no bananas for me :-(

**Comment by jogold** [comment]
Hi @silver2k,

This has been fixed in v1.0.2 normally, are you using the latest version ?

**Comment by colinfindlay-nz** [comment]
I was using 1.10, but maybe one of my machines isn't updated.
I'll double check.

Thanks

**Comment by jogold** [comment]
Hi @silver2k,

Have you checked the version ?

**Comment by colinfindlay-nz** [comment]
Yep - my fault. One dev machine had an old version
