### ISSUE TITLE
Nothing Happens

### ISSUE THREAD

**Issue by arb** [goldwasserexchange/serverless-plugin-webpack#19]
If I put a log statement in the `webpackBundle` function, it is never called during a deployment. I am using `serverless@1.11.0` and `serverless-plugin-webpack@1.1.0`. 

I added:
```
plugins:
  - serverless-plugin-webpack
```

To my serverless.yml and added this webpack.config.js file:

```
module.exports = {
  target: 'node',
  externals: [
    /aws-sdk/,
  ]
};
```

It doesn't appear that the plugin is running or doing anything? Any help would be appreciated.

**Comment by jogold** [comment]
Hi @arb,

Support for serverless < 1.12.0 has been dropped in v1.0.0, see https://github.com/goldwasserexchange/serverless-plugin-webpack/releases

**Comment by arb** [comment]
I updated and now the plugin seems to be working. I'm having other issues, but I'll open a new ticket, thanks!
