### ISSUE TITLE
Feature request: deploy single function.

### ISSUE THREAD

**Issue by shmuga** [goldwasserexchange/serverless-plugin-webpack#2]
First of all thanks for awesome work.
Your plugin works better than https://github.com/elastic-coders/serverless-webpack/ due to less configuration and automatic bundling to a single file.

It would be nice to have a feature to deploy single function to AWS.

The looks like this:
```
serverless deploy function --stage <stage> -f <name>
```

And as I understand from some other issues serverless provides hooks for single function deployment. Do you have any thoughts about this? I will try to make more research in this way.

**Comment by jogold** [comment]
Hi @shmuga,

Thank you for the feedback. I will look into it.

**Comment by shmuga** [comment]
I've looked into last issues on serverless github and found that they have deprecated some of the lifecycle events, that you are currently using. They are trying to separate concepts of packaging and deploying.

You can found changes in master branch.
And disucssions here https://github.com/serverless/serverless/issues/3467

Here all the deprecations https://github.com/serverless/serverless/blob/master/lib/plugins/deploy/deploy.js#L17

New lifecycle events here https://github.com/serverless/serverless/blob/master/lib/plugins/package/package.js#L64

**Comment by jogold** [comment]
That's correct. I'm following this and will try to update the plugin accordingly.

**Comment by shmuga** [comment]
Awesome! Looking forward to updates.

**Comment by jogold** [comment]
This should be fixed with v1.0.0.
