### ISSUE TITLE
Sls invoke local support

### ISSUE THREAD

**Issue by dbeja** [goldwasserexchange/serverless-plugin-webpack#51]
Does this plugin supports sls invoke local?
When I try to to invoke a function locally it seems the function is not bundled with webpack.

I get this kind of errors:
`SyntaxError: Unexpected token import`

**Comment by dbeja** [comment]
Any update on this?

**Comment by jogold** [comment]
Hi @dbeja,

Invoke local is currently not supported. I will have a look at it.

**Comment by hagen** [comment]
@dbeja I think that's because you're using ES6? Node doesn't support import/export statements without a transpiler (Babel), so local tests won't work unless you firstly transpile.
@jogold this is probably one of the most needed enhancements now - a webpack compile step before tests or local invoke
