### ISSUE TITLE
Support for Webpack 4.x

### ISSUE THREAD

**Issue by cardoni** [goldwasserexchange/serverless-plugin-webpack#52]
Webpack 4.x introduces a new `mode` concept that can be set to `development` or `production`.  Any plans to support this?

**Comment by jogold** [comment]
Hi @cardoni,

It should work with the plugin. Just set `mode` in your `webpack.config.js`.

Do you think the plugin should set a default value?

**Comment by jogold** [comment]
Closing for now. Feel free to reopen if you still have issues with webpack 4.x.
